apiVersion: v1
kind: ServiceAccount
metadata:
  name: clean-up-sa
  namespace: scen2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clean-up-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clean-up-binding
subjects:
  - kind: ServiceAccount
    name: clean-up-sa
    namespace: scen2
roleRef:
  kind: ClusterRole
  name: clean-up-role
  apiGroup: rbac.authorization.k8s.io
