apiVersion: batch/v1
kind: CronJob
metadata:
  name: all
  namespace: automated-testing
spec:
  schedule: "0 0 31 2 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cra
            image: nginx:1.14.1
            ports:
            - containerPort: 80
          - name: sca
            image: busybox
            command: ["sleep", "999999"]
          - name: runtest
            image: busybox
            command: ["/bin/sh", "-c", "cat /etc/testconfig/* && sleep 10"]
            volumeMounts:
            - mountPath: /etc/testconfig
              name: testconfig
          volumes:
          - name: testconfig
            configMap: 
              name: testconfig
          restartPolicy: Never
