apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim
  namespace: automated-testing
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: sim
  template:
    metadata:
      labels:
        app: sim
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 80
