apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim
  namespace: automated-testing
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
