apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-clean-up-
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["sleep", "180"] 
      restartPolicy: Never