apiVersion: batch/v1
kind: Job
metadata:
  name: test123
  # generateName: job-clean-up-
  namespace: scen2
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      serviceAccountName: clean-up-sa
      containers:
      - name: clean-up-job
        image: bitnami/kubectl:latest  # You can use any image with kubectl
        command:
          - /bin/sh
          - -c
          - |
            echo "Scaling down deployment..."
            kubectl get namespace
            kubectl get jobs -n scen2
            # kubectl scale deployment nginx-deployment --replicas=0 -n scen2
      restartPolicy: Never