apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-run-tests-
  namespace: scen2
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["sleep", "180"] 
      restartPolicy: Never