apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: test1
    repoURL: 'https://github.com/milosveljkovic/test-argojobs'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true