apiVersion: apps/v1
kind: Deployment
metadata:
  name: cra-and-sca
  namespace: automated-testing
spec:
  selector:
    matchLabels:
      app: cra-and-sca
  template:
    metadata:
      labels:
        app: cra-and-sca
    spec:
      containers:
      - name: cra
        image: nginx:1.14.1
        ports:
        - containerPort: 80
      - name: sca
        image: busybox
        command: ["sleep", "999999"]
      - name: test
        image: busybox
        command: ["sleep", "10"]
      restartPolicy: "Always"