apiVersion: batch/v1
kind: Job
metadata:
  name: clean-up
  namespace: automated-testing
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      serviceAccountName: clean-up-sa
      containers:
      - name: clean-up-job
        image: bitnami/kubectl:latest  # You can use any image with kubectl
        command:
          - /bin/sh
          - -c
          - |
            echo "Scaling down deployment..."
            kubectl get namespace
            kubectl get jobs -n automated-testing
            echo "Stop simulator..."
            kubectl scale deployment sim --replicas=0 -n automated-testing
      restartPolicy: Never