apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-job
  namespace: automated-testing
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      serviceAccountName: clean-up-sa
      containers:
      - name: clean-up-job
        image: bitnami/kubectl:latest  # You can use any image with kubectl
        command:
          - /bin/sh
          - -c
          - |
            echo "Scaling up deployments..."
            kubectl get namespace
            kubectl get jobs -n automated-testing
            echo "Stop simulator..."
            kubectl scale deployment sim --replicas=1 -n automated-testing
            kubectl scale deployment cra-and-sca --replicas=1 -n automated-testing
      restartPolicy: Never