apiVersion: batch/v1
kind: Job
metadata:
  namespace: automated-testing
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: run-test
        image: busybox
        command: ["sleep", "30"] 
      restartPolicy: Never